apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service
  namespace: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: auth-service-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: togglemaster/homolog/auth-db
        property: DATABASE_URL
    - secretKey: MASTER_KEY
      remoteRef:
        key: togglemaster/homolog/application
        property: MASTER_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flag-service
  namespace: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: flag-service-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: togglemaster/homolog/flag-db
        property: DATABASE_URL
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: targeting-service
  namespace: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: targeting-service-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: togglemaster/homolog/targeting-db
        property: DATABASE_URL
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: application
  namespace: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: togglemaster-application-secret
    creationPolicy: Owner
  data:
    - secretKey: SERVICE_API_KEY
      remoteRef:
        key: togglemaster/homolog/application
        property: SERVICE_API_KEY
    - secretKey: AWS_REGION
      remoteRef:
        key: togglemaster/homolog/runtime
        property: AWS_REGION
    - secretKey: AWS_SQS_URL
      remoteRef:
        key: togglemaster/homolog/runtime
        property: AWS_SQS_URL
    - secretKey: AWS_DYNAMODB_TABLE
      remoteRef:
        key: togglemaster/homolog/runtime
        property: AWS_DYNAMODB_TABLE
    - secretKey: REDIS_URL
      remoteRef:
        key: togglemaster/homolog/runtime
        property: REDIS_URL
    - secretKey: FLAG_SERVICE_URL
      remoteRef:
        key: togglemaster/homolog/runtime
        property: FLAG_SERVICE_URL
    - secretKey: TARGETING_SERVICE_URL
      remoteRef:
        key: togglemaster/homolog/runtime
        property: TARGETING_SERVICE_URL
    - secretKey: AUTH_SERVICE_URL
      remoteRef:
        key: togglemaster/homolog/runtime
        property: AUTH_SERVICE_URL
