apiVersion: v1
kind: Service
metadata:
  name: targeting-service
  namespace: togglemaster
spec:
  selector:
    app.kubernetes.io/name: targeting-service
  ports:
    - name: http
      port: 8003
      targetPort: http
