apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: service-image
    newName: 560109405379.dkr.ecr.us-east-1.amazonaws.com/auth-service
    newTag: 7edbee1ce26ef14b439e14412880659bb72212a7
