apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: service-image
    newName: 560109405379.dkr.ecr.us-east-1.amazonaws.com/flag-service
    newTag: fd41560027b8f8a9a2331cbb6bb994a2a5ed3dd4
