apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: togglemaster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amandafo/POS_FIAP_FASE_03.git
    targetRevision: main
    path: gitops/argocd/applications
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    retry: { limit: 5 }
